<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-N9N8M7C" failures="2" tests="3" name="AddCustomerLoginTest" time="25.734" errors="0" timestamp="2023-10-08T07:58:46 IST">
  <testcase classname="testCases.TC_002_AddCustomerLoginTest" name="addCustomer" time="1.044"/>
  <testcase classname="testCases.TC_002_AddCustomerLoginTest" name="addCustomer" time="10.074">
    <failure type="java.lang.AssertionError" message="Customer not added successfully">
      <![CDATA[java.lang.AssertionError: Customer not added successfully
at testCases.TC_002_AddCustomerLoginTest.addCustomer(TC_002_AddCustomerLoginTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase classname="testCases.TC_002_AddCustomerLoginTest" name="addCustomer" time="10.082">
    <failure type="java.lang.AssertionError" message="Customer not added successfully">
      <![CDATA[java.lang.AssertionError: Customer not added successfully
at testCases.TC_002_AddCustomerLoginTest.addCustomer(TC_002_AddCustomerLoginTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
</testsuite> <!-- AddCustomerLoginTest -->
