<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-08T08:03:49 IST" name="Failed suite [Data Driven Test]" finished-at="2023-10-08T08:04:08 IST" duration-ms="18597">
    <groups>
    </groups>
    <test started-at="2023-10-08T08:03:49 IST" name="AddCustomerLoginTest(failed)" finished-at="2023-10-08T08:04:08 IST" duration-ms="18597">
      <class name="testCases.TC_002_AddCustomerLoginTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testCases.TC_002_AddCustomerLoginTest@4b8729ff]" started-at="2023-10-08T08:03:50 IST" name="setup" finished-at="2023-10-08T08:03:55 IST" duration-ms="4998" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="addCustomer(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC_002_AddCustomerLoginTest@4b8729ff]" started-at="2023-10-08T08:03:56 IST" name="addCustomer" data-provider="LoginData" finished-at="2023-10-08T08:03:58 IST" duration-ms="1144" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Bat]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[setti]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[WE45opop]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method signature="addCustomer(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC_002_AddCustomerLoginTest@4b8729ff]" started-at="2023-10-08T08:03:58 IST" name="addCustomer" data-provider="LoginData" finished-at="2023-10-08T08:04:08 IST" duration-ms="10075" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Cat]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[setti]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[As1256fp]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer not added successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer not added successfully
at org.testng.Assert.fail(Assert.java:99)
at testCases.TC_002_AddCustomerLoginTest.addCustomer(TC_002_AddCustomerLoginTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_002_AddCustomerLoginTest@4b8729ff]" started-at="2023-10-08T08:04:08 IST" name="tearDown" finished-at="2023-10-08T08:04:08 IST" duration-ms="260" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_002_AddCustomerLoginTest -->
    </test> <!-- AddCustomerLoginTest(failed) -->
  </suite> <!-- Failed suite [Data Driven Test] -->
</testng-results>
